name: abcbul
description: A new Flutter project.
version: 1.0.0+3
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  webview_flutter: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400

#description: A new Flutter project.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#
#version: 1.0.0+2
#
#environment:
#  sdk: '>=3.1.5 <4.0.0'
#
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#  cupertino_icons: ^1.0.2
#  path_provider: ^2.1.1
#  flutter_launcher_icons: ^0.13.1
#  device_preview: ^1.1.0
#  font_awesome_flutter: ^10.6.0
#  google_fonts: ^6.1.0
#  flutter_svg: ^2.0.5
#  http: ^1.1.2
#  shared_preferences: ^2.2.2
#  provider: ^6.1.1
#  fluttertoast: ^8.2.4
#  rounded_loading_button: ^2.1.0
#  flutter_countdown_timer: ^4.1.0
#  timer_count_down: ^2.2.2
#  image_picker: ^1.0.7
#  flutter_native_splash: ^2.3.10
#
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "images/play_store_512.png"
#flutter_native_splash:
#
#  color: "#141414 "  # You can remove or keep the color parameter based on your preference.
##  background_image: "images/background.png"
#  image: "images/background.png"
#
#
#
#flutter_lints: ^2.0.0
#
#
#flutter:
#
#
#  uses-material-design: true
#
#  # To add assets to your application, add an assets section, like this:
#  assets:
#    - images/
#
